# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI (Go)

on:
  pull_request:
    branches: ["main", "development"]
  push:
    branches: ["main", "development"]
    
jobs:
 build:
    name: Build and Test (Go)
    permissions:
      contents: read
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v4

    - name: Set up Go (1.24.0)
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'
        check-latest: true
        cache-dependency-path: ./go.sum
    
    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./...
